project:
  type: website

website:
  title: "DIY Regression"
  favicon: favicon/regression.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Regression Types"
        menu:
          - href: regressions/linear.qmd
            text: linear
          - href: regressions/probit.qmd
            text: probit
          - href: regressions/negative-binomial.qmd
            text: negative binomial
          - href: regressions/logistic.qmd
            text: logistic
          - href: regressions/poisson.qmd
            text: poisson
          - href: regressions/zipoisson.qmd
            text: zero-inflated poisson
    tools:
      - icon: github
        url: https://github.com/jasminesis/regression
  sidebar:
    style: "docked"
    contents:
      - section: "Regression Types"
        contents:
          - href: regressions/linear.qmd
            text: linear
          - href: regressions/probit.qmd
            text: probit
          - href: regressions/negative-binomial.qmd
            text: negative binomial
          - href: regressions/logistic.qmd
            text: logistic
          - href: regressions/poisson.qmd
            text: poisson
          - href: regressions/zipoisson.qmd
            text: zero-inflated poisson
      - href: note.qmd
        text: "A Note"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
